// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <stdio.h>
#include <string.h>

// Variables globales para las calibraciones
extern bool brightness_calibration_mode;
extern bool nrf24_calibration_mode;
extern bool palanca1_calibration_mode;
extern bool palanca2_calibration_mode;
extern bool palanca3_calibration_mode;
extern bool palanca4_calibration_mode;
extern bool settings_calibration_mode;
extern bool intensidad_calibration_mode;

// Funciones wrapper declaradas en main.cpp
extern void applyBrightness(int brightness_value);
extern uint8_t getBrightnessLimit(void);
extern void setBrightnessLimit(uint8_t value);
extern void saveCurrentConfig(void);
extern uint64_t getNRFAddress(void);
extern void setNRFAddress(uint64_t address);
extern void getTurnLimits(uint8_t* pos1, uint8_t* pos2, uint8_t* pos3);
extern void setTurnLimits(uint8_t pos1, uint8_t pos2, uint8_t pos3);
extern void getSpeedLimits(uint8_t* pos1, uint8_t* pos2, uint8_t* pos3);
extern void setSpeedLimits(uint8_t pos1, uint8_t pos2, uint8_t pos3);
extern void getBoostLimits(uint8_t* pos1, uint8_t* pos2, uint8_t* pos3);
extern void setBoostLimits(uint8_t pos1, uint8_t pos2, uint8_t pos3);
extern void getExtraLimits(uint8_t* pos1, uint8_t* pos2, uint8_t* pos3);
extern void setExtraLimits(uint8_t pos1, uint8_t pos2, uint8_t pos3);
extern void setActiveProfile(uint8_t profile);
extern uint8_t getActiveProfile(void);
extern void setIntensity(uint8_t intensity);
extern uint8_t getIntensityLimit(void);
extern void clearAllProfiles(void);
extern bool repairProfile(uint8_t profile);

// Variables para calibración de brillo
static uint8_t original_brightness = 0;
static uint8_t current_brightness = 0;

// Variables para calibración NRF24
static uint64_t original_nrf_address = 0;

// Variables para calibración palanca1
static uint8_t original_turn_limits[3] = {0, 0, 0};
static uint8_t current_turn_limits[3] = {0, 0, 0};
static uint8_t current_position = 0; // 0=pos1, 1=pos2, 2=pos3

// Variables para calibración palanca2 (dirección)
static uint8_t original_speed_limits[3] = {0, 0, 0};
static uint8_t current_speed_limits[3] = {0, 0, 0};
static uint8_t current_direction_position = 0; // 0=pos1, 1=pos2, 2=pos3

// Variables para calibración palanca3 (boost)
static uint8_t original_boost_limits[3] = {0, 0, 0};
static uint8_t current_boost_limits[3] = {0, 0, 0};
static uint8_t current_boost_position = 0; // 0=pos1, 1=pos2, 2=pos3

// Variables para calibración palanca4 (extra)
static uint8_t original_extra_limits[3] = {0, 0, 0};
static uint8_t current_extra_limits[3] = {0, 0, 0};
static uint8_t current_extra_position = 0; // 0=pos1, 1=pos2, 2=pos3

// Variables para calibración de settings
static uint8_t original_active_profile = 0;

// Variables para calibración de intensidad
static uint8_t original_intensity = 1;

void Button1_event_cb(lv_event_t * e)
{
    // Disminuir brillo solo si estamos en modo calibración de brillo
    if (brightness_calibration_mode) {
        if (current_brightness > 0) {
            current_brightness--;
            applyBrightness(current_brightness);
            
            // Actualizar TextArea3 con el nuevo valor
            char brightness_str[4];
            sprintf(brightness_str, "%d", current_brightness);
            lv_textarea_set_text(ui_TextArea3, brightness_str);
        }
    }
    
    // Disminuir valor de posición de palanca1 si estamos en modo calibración
    if (palanca1_calibration_mode) {
        if (current_turn_limits[current_position] > 0) {
            current_turn_limits[current_position]--;
            
            // Actualizar TextArea3 con el nuevo valor
            char position_str[4];
            sprintf(position_str, "%d", current_turn_limits[current_position]);
            lv_textarea_set_text(ui_TextArea3, position_str);
        }
    }
    
    // Disminuir valor de posición de palanca2 (dirección) si estamos en modo calibración
    if (palanca2_calibration_mode) {
        if (current_speed_limits[current_direction_position] > 0) {
            current_speed_limits[current_direction_position]--;
            
            // Actualizar TextArea3 con el nuevo valor
            char direction_str[4];
            sprintf(direction_str, "%d", current_speed_limits[current_direction_position]);
            lv_textarea_set_text(ui_TextArea3, direction_str);
        }
    }
    
    // Disminuir valor de posición de palanca3 (boost) si estamos en modo calibración
    if (palanca3_calibration_mode) {
        if (current_boost_limits[current_boost_position] > 0) {
            current_boost_limits[current_boost_position]--;
            
            // Actualizar TextArea3 con el nuevo valor
            char boost_str[4];
            sprintf(boost_str, "%d", current_boost_limits[current_boost_position]);
            lv_textarea_set_text(ui_TextArea3, boost_str);
        }
    }
    
    // Disminuir valor de posición de palanca4 (extra) si estamos en modo calibración
    if (palanca4_calibration_mode) {
        if (current_extra_limits[current_extra_position] > 0) {
            current_extra_limits[current_extra_position]--;
            
            // Actualizar TextArea3 con el nuevo valor
            char extra_str[4];
            sprintf(extra_str, "%d", current_extra_limits[current_extra_position]);
            lv_textarea_set_text(ui_TextArea3, extra_str);
        }
    }
}

void Button2_event_cb(lv_event_t * e)
{
    // Aumentar brillo solo si estamos en modo calibración de brillo
    if (brightness_calibration_mode) {
        if (current_brightness < 255) {
            current_brightness++;
            applyBrightness(current_brightness);
            
            // Actualizar TextArea3 con el nuevo valor
            char brightness_str[4];
            sprintf(brightness_str, "%d", current_brightness);
            lv_textarea_set_text(ui_TextArea3, brightness_str);
        }
    }
    
    // Aumentar valor de posición de palanca1 si estamos en modo calibración
    if (palanca1_calibration_mode) {
        if (current_turn_limits[current_position] < 255) {
            current_turn_limits[current_position]++;
            
            // Actualizar TextArea3 con el nuevo valor
            char position_str[4];
            sprintf(position_str, "%d", current_turn_limits[current_position]);
            lv_textarea_set_text(ui_TextArea3, position_str);
        }
    }
    
    // Aumentar valor de posición de palanca2 (dirección) si estamos en modo calibración
    if (palanca2_calibration_mode) {
        if (current_speed_limits[current_direction_position] < 255) {
            current_speed_limits[current_direction_position]++;
            
            // Actualizar TextArea3 con el nuevo valor
            char direction_str[4];
            sprintf(direction_str, "%d", current_speed_limits[current_direction_position]);
            lv_textarea_set_text(ui_TextArea3, direction_str);
        }
    }
    
    // Aumentar valor de posición de palanca3 (boost) si estamos en modo calibración
    if (palanca3_calibration_mode) {
        if (current_boost_limits[current_boost_position] < 255) {
            current_boost_limits[current_boost_position]++;
            
            // Actualizar TextArea3 con el nuevo valor
            char boost_str[4];
            sprintf(boost_str, "%d", current_boost_limits[current_boost_position]);
            lv_textarea_set_text(ui_TextArea3, boost_str);
        }
    }
    
    // Aumentar valor de posición de palanca4 (extra) si estamos en modo calibración
    if (palanca4_calibration_mode) {
        if (current_extra_limits[current_extra_position] < 255) {
            current_extra_limits[current_extra_position]++;
            
            // Actualizar TextArea3 con el nuevo valor
            char extra_str[4];
            sprintf(extra_str, "%d", current_extra_limits[current_extra_position]);
            lv_textarea_set_text(ui_TextArea3, extra_str);
        }
    }
}

void calibrar_brillo(lv_event_t * e)
{
    // Activar modo calibración de brillo
    brightness_calibration_mode = true;
    
    // Cambiar Label4 a "Calibrar Brillo"
    lv_label_set_text(ui_Label4, "Calibrar Brillo");
    
    // Obtener el valor actual del brillo guardado
    original_brightness = getBrightnessLimit();
    current_brightness = original_brightness;
    
    // Mostrar el valor actual en TextArea3
    char brightness_str[4];
    sprintf(brightness_str, "%d", current_brightness);
    lv_textarea_set_text(ui_TextArea3, brightness_str);
}

void calibrate_nrf24(lv_event_t * e)
{
    // Activar modo calibración NRF24
    nrf24_calibration_mode = true;
    
    // Guardar el valor original para poder restaurarlo si se cancela
    original_nrf_address = getNRFAddress();
    
    // Configurar el TextArea1 y Keyboard1
    lv_obj_t * ta = ui_TextArea1;   
    lv_obj_t * kb = ui_Keyboard1;   

    lv_keyboard_set_textarea(kb, ta);
    
    // Convertir el valor uint64_t a formato hexadecimal string
    char nrf_str[20];
    sprintf(nrf_str, "0x%010llX", original_nrf_address);
    
    // Establecer el valor en el TextArea1
    lv_textarea_set_text(ta, nrf_str);
    
    // Configurar el TextArea para permitir solo caracteres hexadecimales
    lv_textarea_set_accepted_chars(ta, "0123456789ABCDEFabcdefxX");
    
    // Posicionar el cursor al final
    lv_textarea_set_cursor_pos(ta, LV_TEXTAREA_CURSOR_LAST);
}

void calibrate_joystick(lv_event_t * e)
{
    // Activar modo calibración palanca1
    palanca1_calibration_mode = true;
    
    // Obtener los valores actuales de las posiciones
    getTurnLimits(&original_turn_limits[0], &original_turn_limits[1], &original_turn_limits[2]);
    
    // Copiar valores originales a los actuales
    current_turn_limits[0] = original_turn_limits[0];
    current_turn_limits[1] = original_turn_limits[1];
    current_turn_limits[2] = original_turn_limits[2];
}

void calibrar_direccion(lv_event_t * e)
{
    // Activar modo calibración palanca2 (dirección)
    palanca2_calibration_mode = true;
    
    // Obtener los valores actuales de las posiciones de velocidad/dirección
    getSpeedLimits(&original_speed_limits[0], &original_speed_limits[1], &original_speed_limits[2]);
    
    // Copiar valores originales a los actuales
    current_speed_limits[0] = original_speed_limits[0];
    current_speed_limits[1] = original_speed_limits[1];
    current_speed_limits[2] = original_speed_limits[2];
}

void calibrate_boost(lv_event_t * e)
{
    // Activar modo calibración palanca3 (boost)
    palanca3_calibration_mode = true;
    
    // Obtener los valores actuales de las posiciones de boost
    getBoostLimits(&original_boost_limits[0], &original_boost_limits[1], &original_boost_limits[2]);
    
    // Copiar valores originales a los actuales
    current_boost_limits[0] = original_boost_limits[0];
    current_boost_limits[1] = original_boost_limits[1];
    current_boost_limits[2] = original_boost_limits[2];
}

void calibrate_extra(lv_event_t * e)
{
    // Activar modo calibración palanca4 (extra)
    palanca4_calibration_mode = true;
    
    // Obtener los valores actuales de las posiciones de extra
    getExtraLimits(&original_extra_limits[0], &original_extra_limits[1], &original_extra_limits[2]);
    
    // Copiar valores originales a los actuales
    current_extra_limits[0] = original_extra_limits[0];
    current_extra_limits[1] = original_extra_limits[1];
    current_extra_limits[2] = original_extra_limits[2];
}

void calibrar_settings(lv_event_t * e)
{
    // Activar modo calibración de settings (perfiles)
    settings_calibration_mode = true;
    
    // Guardar el perfil activo original para poder restaurarlo si se cancela
    original_active_profile = getActiveProfile();
    
    // Cambiar Label4 a "Seleccionar Perfil"
    lv_label_set_text(ui_Label23, "Seleccionar Perfil");
    // Mostrar el perfil actual en Label23 (convertir 0-3 a 1-4 para mostrar)
    char label_str[32];
    sprintf(label_str, "Perfil %d activo", original_active_profile + 1);  // Sumar 1 para mostrar 1-4
    lv_label_set_text(ui_Label23, label_str);


}

void calibrate_settings1(lv_event_t * e)
{
    if (settings_calibration_mode) {
        // Activar perfil 0 (mostrado como "Perfil 1")
        setActiveProfile(0);
        
        // Desactivar modo calibración
        settings_calibration_mode = false;
        
        // Actualizar Label
        lv_label_set_text(ui_Label23, "Perfil 1 Activado");
        lv_textarea_set_text(ui_TextArea3, "0");
    }
}

void calibrate_settings2(lv_event_t * e)
{
    if (settings_calibration_mode) {
        // Activar perfil 1 (mostrado como "Perfil 2")
        setActiveProfile(1);
        
        // Desactivar modo calibración
        settings_calibration_mode = false;
        
        // Actualizar Label
        lv_label_set_text(ui_Label23, "Perfil 2 Activado");
        lv_textarea_set_text(ui_TextArea3, "1");
    }
}

void calibrate_settings3(lv_event_t * e)
{
    if (settings_calibration_mode) {
        // Activar perfil 2 (mostrado como "Perfil 3")
        setActiveProfile(2);
        
        // Desactivar modo calibración
        settings_calibration_mode = false;
        
        // Actualizar Label
        lv_label_set_text(ui_Label23, "Perfil 3 Activado");
        lv_textarea_set_text(ui_TextArea3, "2");
    }
}

void calibrate_settings4(lv_event_t * e)
{
    if (settings_calibration_mode) {
        // Activar perfil 3 (mostrado como "Perfil 4")
        setActiveProfile(3);
        
        // Desactivar modo calibración
        settings_calibration_mode = false;
        
        // Actualizar Label
        lv_label_set_text(ui_Label23, "Perfil 4 Activado");
        lv_textarea_set_text(ui_TextArea3, "3");
    }
}

void calibrate_posicion1(lv_event_t * e)
{
    if (palanca1_calibration_mode) {
        current_position = 0; // Posición 1
        
        // Cambiar Label4 a "Calibracion Posicion 1"
        lv_label_set_text(ui_Label4, "Calibracion Posicion 1");
        
        // Mostrar el valor actual en TextArea3
        char position_str[4];
        sprintf(position_str, "%d", current_turn_limits[0]);
        lv_textarea_set_text(ui_TextArea3, position_str);
    }
    
    if (palanca2_calibration_mode) {
        current_direction_position = 0; // Posición 1 de dirección
        
        // Cambiar Label4 a "Calibracion Direccion 1"
        lv_label_set_text(ui_Label4, "Calibracion Direccion 1");
        
        // Mostrar el valor actual en TextArea3
        char direction_str[4];
        sprintf(direction_str, "%d", current_speed_limits[0]);
        lv_textarea_set_text(ui_TextArea3, direction_str);
    }
    
    if (palanca3_calibration_mode) {
        current_boost_position = 0; // Posición 1 de boost
        
        // Cambiar Label4 a "Calibracion Boost 1"
        lv_label_set_text(ui_Label4, "Calibracion Boost 1");
        
        // Mostrar el valor actual en TextArea3
        char boost_str[4];
        sprintf(boost_str, "%d", current_boost_limits[0]);
        lv_textarea_set_text(ui_TextArea3, boost_str);
    }
    
    if (palanca4_calibration_mode) {
        current_extra_position = 0; // Posición 1 de extra
        
        // Cambiar Label4 a "Calibracion Extra 1"
        lv_label_set_text(ui_Label4, "Calibracion Extra 1");
        
        // Mostrar el valor actual en TextArea3
        char extra_str[4];
        sprintf(extra_str, "%d", current_extra_limits[0]);
        lv_textarea_set_text(ui_TextArea3, extra_str);
    }
}

void calibrate_posicion2(lv_event_t * e)
{
    if (palanca1_calibration_mode) {
        current_position = 1; // Posición 2
        
        // Cambiar Label4 a "Calibracion Posicion 2"
        lv_label_set_text(ui_Label4, "Calibracion Posicion 2");
        
        // Mostrar el valor actual en TextArea3
        char position_str[4];
        sprintf(position_str, "%d", current_turn_limits[1]);
        lv_textarea_set_text(ui_TextArea3, position_str);
    }
    
    if (palanca2_calibration_mode) {
        current_direction_position = 1; // Posición 2 de dirección
        
        // Cambiar Label4 a "Calibracion Direccion 2"
        lv_label_set_text(ui_Label4, "Calibracion Direccion 2");
        
        // Mostrar el valor actual en TextArea3
        char direction_str[4];
        sprintf(direction_str, "%d", current_speed_limits[1]);
        lv_textarea_set_text(ui_TextArea3, direction_str);
    }
    
    if (palanca3_calibration_mode) {
        current_boost_position = 1; // Posición 2 de boost
        
        // Cambiar Label4 a "Calibracion Boost 2"
        lv_label_set_text(ui_Label4, "Calibracion Boost 2");
        
        // Mostrar el valor actual en TextArea3
        char boost_str[4];
        sprintf(boost_str, "%d", current_boost_limits[1]);
        lv_textarea_set_text(ui_TextArea3, boost_str);
    }
    
    if (palanca4_calibration_mode) {
        current_extra_position = 1; // Posición 2 de extra
        
        // Cambiar Label4 a "Calibracion Extra 2"
        lv_label_set_text(ui_Label4, "Calibracion Extra 2");
        
        // Mostrar el valor actual en TextArea3
        char extra_str[4];
        sprintf(extra_str, "%d", current_extra_limits[1]);
        lv_textarea_set_text(ui_TextArea3, extra_str);
    }
}

void calibrate_posicion3(lv_event_t * e)
{
    if (palanca1_calibration_mode) {
        current_position = 2; // Posición 3
        
        // Cambiar Label4 a "Calibracion Posicion 3"
        lv_label_set_text(ui_Label4, "Calibracion Posicion 3");
        
        // Mostrar el valor actual en TextArea3
        char position_str[4];
        sprintf(position_str, "%d", current_turn_limits[2]);
        lv_textarea_set_text(ui_TextArea3, position_str);
    }
    
    if (palanca2_calibration_mode) {
        current_direction_position = 2; // Posición 3 de dirección
        
        // Cambiar Label4 a "Calibracion Direccion 3"
        lv_label_set_text(ui_Label4, "Calibracion Direccion 3");
        
        // Mostrar el valor actual en TextArea3
        char direction_str[4];
        sprintf(direction_str, "%d", current_speed_limits[2]);
        lv_textarea_set_text(ui_TextArea3, direction_str);
    }
    
    if (palanca3_calibration_mode) {
        current_boost_position = 2; // Posición 3 de boost
        
        // Cambiar Label4 a "Calibracion Boost 3"
        lv_label_set_text(ui_Label4, "Calibracion Boost 3");
        
        // Mostrar el valor actual en TextArea3
        char boost_str[4];
        sprintf(boost_str, "%d", current_boost_limits[2]);
        lv_textarea_set_text(ui_TextArea3, boost_str);
    }
    
    if (palanca4_calibration_mode) {
        current_extra_position = 2; // Posición 3 de extra
        
        // Cambiar Label4 a "Calibracion Extra 3"
        lv_label_set_text(ui_Label4, "Calibracion Extra 3");
        
        // Mostrar el valor actual en TextArea3
        char extra_str[4];
        sprintf(extra_str, "%d", current_extra_limits[2]);
        lv_textarea_set_text(ui_TextArea3, extra_str);
    }
}

void touch_calibrate(lv_event_t * e)
{
    // Función de diagnóstico y limpieza
    static uint32_t press_time = 0;
    static bool pressed = false;
    static uint8_t debug_counter = 0;
    
    lv_event_code_t code = lv_event_get_code(e);
    
    if (code == LV_EVENT_PRESSED) {
        press_time = lv_tick_get();
        pressed = true;
        lv_label_set_text(ui_Label4, "Diagnosticando...");
    }
    else if (code == LV_EVENT_RELEASED) {
        uint32_t hold_time = lv_tick_get() - press_time;
        
        if (pressed && hold_time > 3000) {
            // Mantuvieron presionado por más de 3 segundos - LIMPIAR TODO
            lv_label_set_text(ui_Label4, "LIMPIANDO PERFILES!");
            clearAllProfiles();
            lv_label_set_text(ui_Label4, "PERFILES LIMPIADOS");
            lv_textarea_set_text(ui_TextArea3, "RESTART");
        }
        else if (pressed && hold_time > 1000) {
            // 1-3 segundos - TEST DE GUARDADO
            debug_counter++;
            
            // Cambiar algunos valores para probar
            setBrightnessLimit(50 + (debug_counter * 10));
            setIntensity((debug_counter % 4) + 1);
            
            // Guardar
            saveCurrentConfig();
            
            // Mostrar resultado
            char debug_msg[50];
            sprintf(debug_msg, "TEST %d - B:%d I:%d", debug_counter, 
                   getBrightnessLimit(), getIntensityLimit());
            lv_label_set_text(ui_Label4, debug_msg);
            
            char counter_str[10];
            sprintf(counter_str, "%d", debug_counter);
            lv_textarea_set_text(ui_TextArea3, counter_str);
        }
        else {
            // Toque rápido - mostrar info del perfil actual
            uint8_t profile = getActiveProfile();
            uint8_t brightness = getBrightnessLimit();
            uint8_t intensity = getIntensityLimit();
            
            char info_msg[50];
            sprintf(info_msg, "P:%d B:%d I:%d", profile, brightness, intensity);
            lv_label_set_text(ui_Label4, info_msg);
            
            char profile_str[10];
            sprintf(profile_str, "%d", profile);
            lv_textarea_set_text(ui_TextArea3, profile_str);
        }
        pressed = false;
    }
}

void cancelar_cambios(lv_event_t * e)
{
    // Cancelar cambios de brillo si estamos en modo calibración de brillo
    if (brightness_calibration_mode) {
        // Restaurar el brillo original sin guardar cambios
        current_brightness = original_brightness;
        applyBrightness(original_brightness);
        
        // Actualizar TextArea3 con el valor original
        char brightness_str[4];
        sprintf(brightness_str, "%d", original_brightness);
        lv_textarea_set_text(ui_TextArea3, brightness_str);
        
        // Salir del modo calibración
        brightness_calibration_mode = false;
    }
    
    // Cancelar cambios de NRF24 si estamos en modo calibración NRF24
    if (nrf24_calibration_mode) {
        // Restaurar la dirección NRF original sin guardar cambios
        char nrf_str[20];
        sprintf(nrf_str, "0x%010llX", original_nrf_address);
        lv_textarea_set_text(ui_TextArea1, nrf_str);
        
        // Salir del modo calibración
        nrf24_calibration_mode = false;
    }
    
    // Cancelar cambios de palanca1 si estamos en modo calibración palanca1
    if (palanca1_calibration_mode) {
        // Restaurar valores originales sin guardar cambios
        current_turn_limits[0] = original_turn_limits[0];
        current_turn_limits[1] = original_turn_limits[1];
        current_turn_limits[2] = original_turn_limits[2];
        
        // Actualizar TextArea3 con el valor original de la posición actual
        char position_str[4];
        sprintf(position_str, "%d", original_turn_limits[current_position]);
        lv_textarea_set_text(ui_TextArea3, position_str);
        
        // Salir del modo calibración
        palanca1_calibration_mode = false;
    }
    
    // Cancelar cambios de palanca2 (dirección) si estamos en modo calibración palanca2
    if (palanca2_calibration_mode) {
        // Restaurar valores originales sin guardar cambios
        current_speed_limits[0] = original_speed_limits[0];
        current_speed_limits[1] = original_speed_limits[1];
        current_speed_limits[2] = original_speed_limits[2];
        
        // Actualizar TextArea3 con el valor original de la posición actual
        char direction_str[4];
        sprintf(direction_str, "%d", original_speed_limits[current_direction_position]);
        lv_textarea_set_text(ui_TextArea3, direction_str);
        
        // Salir del modo calibración
        palanca2_calibration_mode = false;
    }
    
    // Cancelar cambios de palanca3 (boost) si estamos en modo calibración palanca3
    if (palanca3_calibration_mode) {
        // Restaurar valores originales sin guardar cambios
        current_boost_limits[0] = original_boost_limits[0];
        current_boost_limits[1] = original_boost_limits[1];
        current_boost_limits[2] = original_boost_limits[2];
        
        // Actualizar TextArea3 con el valor original de la posición actual
        char boost_str[4];
        sprintf(boost_str, "%d", original_boost_limits[current_boost_position]);
        lv_textarea_set_text(ui_TextArea3, boost_str);
        
        // Salir del modo calibración
        palanca3_calibration_mode = false;
    }
    
    // Cancelar cambios de palanca4 (extra) si estamos en modo calibración palanca4
    if (palanca4_calibration_mode) {
        // Restaurar valores originales sin guardar cambios
        current_extra_limits[0] = original_extra_limits[0];
        current_extra_limits[1] = original_extra_limits[1];
        current_extra_limits[2] = original_extra_limits[2];
        
        // Actualizar TextArea3 con el valor original de la posición actual
        char extra_str[4];
        sprintf(extra_str, "%d", original_extra_limits[current_extra_position]);
        lv_textarea_set_text(ui_TextArea3, extra_str);
        
        // Salir del modo calibración
        palanca4_calibration_mode = false;
    }
    
    // Cancelar cambios de intensidad si estamos en modo calibración intensidad
    if (intensidad_calibration_mode) {
        // Restaurar la intensidad original sin cambios
        setIntensity(original_intensity);
        
        // Actualizar TextArea3 con el valor original
        char intensity_str[4];
        sprintf(intensity_str, "%d", original_intensity);
        lv_textarea_set_text(ui_TextArea3, intensity_str);
        
        // Salir del modo calibración
        intensidad_calibration_mode = false;
    }
    
    // Cancelar cambios de settings si estamos en modo calibración settings
    if (settings_calibration_mode) {
        // Restaurar el perfil original sin cambios
        setActiveProfile(original_active_profile);
        
        // Actualizar TextArea3 con el valor original
        char profile_str[4];
        sprintf(profile_str, "%d", original_active_profile);
        lv_textarea_set_text(ui_TextArea3, profile_str);
        
        // Salir del modo calibración
        settings_calibration_mode = false;
    }
    
}

void salir_configuracion(lv_event_t * e)
{
    // Desactivar todos los modos de calibración
    brightness_calibration_mode = false;
    nrf24_calibration_mode = false;
    palanca1_calibration_mode = false;
    palanca2_calibration_mode = false;
    palanca3_calibration_mode = false;
    palanca4_calibration_mode = false;
    settings_calibration_mode = false;
    intensidad_calibration_mode = false;
}

void guardarCambios(lv_event_t * e)
{
    // Guardar cambios de brillo si estamos en modo calibración de brillo
    if (brightness_calibration_mode) {
        // Guardar la nueva configuración de brillo
        setBrightnessLimit(current_brightness);
        saveCurrentConfig();
        
        // Salir del modo calibración
        brightness_calibration_mode = false;
    }
    
    // Guardar cambios de NRF24 si estamos en modo calibración NRF24
    if (nrf24_calibration_mode) {
        // Obtener el valor del TextArea1
        const char* nrf_text = lv_textarea_get_text(ui_TextArea1);
        
        // Convertir el string hexadecimal a uint64_t
        uint64_t new_nrf_address = 0;
        if (nrf_text != NULL && strlen(nrf_text) > 2) {
            // Si empieza con "0x", usar sscanf para convertir
            if (nrf_text[0] == '0' && (nrf_text[1] == 'x' || nrf_text[1] == 'X')) {
                sscanf(nrf_text, "%llx", &new_nrf_address);
            } else {
                // Si no tiene "0x", asumimos que es hexadecimal
                sscanf(nrf_text, "%llx", &new_nrf_address);
            }
        }
        
        // Guardar la nueva dirección NRF24
        if (new_nrf_address != 0) {
            setNRFAddress(new_nrf_address);
            saveCurrentConfig();
        }
        
        // Salir del modo calibración
        nrf24_calibration_mode = false;
    }
    
    // Guardar cambios de palanca1 si estamos en modo calibración palanca1
    if (palanca1_calibration_mode) {
        // Guardar los nuevos valores de las posiciones
        setTurnLimits(current_turn_limits[0], current_turn_limits[1], current_turn_limits[2]);
        saveCurrentConfig();
        
        // Salir del modo calibración
        palanca1_calibration_mode = false;
    }
    
    // Guardar cambios de palanca2 (dirección) si estamos en modo calibración palanca2
    if (palanca2_calibration_mode) {
        // Guardar los nuevos valores de las posiciones de dirección
        setSpeedLimits(current_speed_limits[0], current_speed_limits[1], current_speed_limits[2]);
        saveCurrentConfig();
        
        // Salir del modo calibración
        palanca2_calibration_mode = false;
    }
    
    // Guardar cambios de palanca3 (boost) si estamos en modo calibración palanca3
    if (palanca3_calibration_mode) {
        // Guardar los nuevos valores de las posiciones de boost
        setBoostLimits(current_boost_limits[0], current_boost_limits[1], current_boost_limits[2]);
        saveCurrentConfig();
        
        // Salir del modo calibración
        palanca3_calibration_mode = false;
    }
    
    // Guardar cambios de palanca4 (extra) si estamos en modo calibración palanca4
    if (palanca4_calibration_mode) {
        // Guardar los nuevos valores de las posiciones de extra
        setExtraLimits(current_extra_limits[0], current_extra_limits[1], current_extra_limits[2]);
        saveCurrentConfig();
        
        // Salir del modo calibración
        palanca4_calibration_mode = false;
    }
    
    // Guardar cambios de settings si estamos en modo calibración settings
    if (settings_calibration_mode) {
        // El perfil ya se cambió al seleccionarlo, solo guardar la configuración
        
        saveCurrentConfig();
        
        // Salir del modo calibración
        settings_calibration_mode = false;
    }
    
    // Guardar cambios de intensidad si estamos en modo calibración intensidad
    if (intensidad_calibration_mode) {
        // La intensidad ya se guardó al seleccionarla, solo confirmar guardado
        saveCurrentConfig();
        
        // Salir del modo calibración
        intensidad_calibration_mode = false;
    }
}

void calibrar_intensidad(lv_event_t * e)
{
    // Activar modo calibración de intensidad
    intensidad_calibration_mode = true;
    
    // Guardar el valor de intensidad original para poder restaurarlo si se cancela
    original_intensity = getIntensityLimit();
    
    // Mostrar la intensidad actual en Label24 con texto descriptivo
    char intensity_label[32];
    switch(original_intensity) {
        case 1:
            sprintf(intensity_label, "Intensidad Actual: Minimo");
            break;
        case 2:
            sprintf(intensity_label, "Intensidad Actual: Moderado");
            break;
        case 3:
            sprintf(intensity_label, "Intensidad Actual: Normal");
            break;
        case 4:
            sprintf(intensity_label, "Intensidad Actual: Maximo");
            break;
        default:
            sprintf(intensity_label, "Intensidad Actual: Minimo");
            break;
    }
    lv_label_set_text(ui_Label24, intensity_label);
}

void calibrate_intensidad1(lv_event_t * e)
{
    if (intensidad_calibration_mode) {
        // Activar intensidad 1
        setIntensity(1);
        saveCurrentConfig();
        
        // Desactivar modo calibración
        intensidad_calibration_mode = false;
        
        // Actualizar Label24 con texto descriptivo
        lv_label_set_text(ui_Label24, "Intensidad Actual: Minimo");
    }
}

void calibrate_intensidad2(lv_event_t * e)
{
    if (intensidad_calibration_mode) {
        // Activar intensidad 2
        setIntensity(2);
        saveCurrentConfig();
        
        // Desactivar modo calibración
        intensidad_calibration_mode = false;
        
        // Actualizar Label24 con texto descriptivo
        lv_label_set_text(ui_Label24, "Intensidad Actual: Moderado");
    }
}

void calibrate_intensidad3(lv_event_t * e)
{
    if (intensidad_calibration_mode) {
        // Activar intensidad 3
        setIntensity(3);
        saveCurrentConfig();
        
        // Desactivar modo calibración
        intensidad_calibration_mode = false;
        
        // Actualizar Label24 con texto descriptivo
        lv_label_set_text(ui_Label24, "Intensidad Actual: Normal");
    }
}

void _intensidad4(lv_event_t * e)
{
    if (intensidad_calibration_mode) {
        // Activar intensidad 4
        setIntensity(4);
        saveCurrentConfig();
        
        // Desactivar modo calibración
        intensidad_calibration_mode = false;
        
        // Actualizar Label24 con texto descriptivo
        lv_label_set_text(ui_Label24, "Intensidad Actual: Maximo");
    }
}
