// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_Screen4.h"
#include "ui_Screen5.h"
#include "ui_Screen6.h"
#include "ui_Screen7.h"
#include "ui_Screen8.h"
#include "ui_Screen9.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(
    ui_img_settings_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/settings_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(ui_img_145_png);    // assets/145.png
LV_IMG_DECLARE(ui_img_12_png);    // assets/12.png
LV_IMG_DECLARE(
    ui_img_undo_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/undo_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_search_hands_free_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/search_hands_free_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_pin_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/pin_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_brightness_6_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/brightness_6_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_speed_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/speed_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_local_fire_department_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/local_fire_department_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_variable_add_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/variable_add_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_settings_account_box_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/settings_account_box_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_android_cell_4_bar_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/android_cell_4_bar_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_joystick_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/joystick_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_signal_cellular_0_bar_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/signal_cellular_0_bar_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_signal_cellular_1_bar_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/signal_cellular_1_bar_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_signal_cellular_2_bar_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/signal_cellular_2_bar_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_signal_cellular_4_bar_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/signal_cellular_4_bar_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_cell_tower_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);    // assets/cell_tower_50dp_15B9A8_FILL0_wght400_GRAD0_opsz48.png

// FONTS
LV_FONT_DECLARE(ui_font_Alegreya);
LV_FONT_DECLARE(ui_font_Bakemono);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
