// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Button1_event_cb(lv_event_t * e);
void Button2_event_cb(lv_event_t * e);
void calibrar_brillo(lv_event_t * e);
void calibrate_nrf24(lv_event_t * e);
void calibrar_settings(lv_event_t * e);
void calibrar_intensidad(lv_event_t * e);
void calibrate_joystick(lv_event_t * e);
void calibrate_boost(lv_event_t * e);
void calibrate_extra(lv_event_t * e);
void calibrar_direccion(lv_event_t * e);
void cancelar_cambios(lv_event_t * e);
void salir_configuracion(lv_event_t * e);
void guardarCambios(lv_event_t * e);
void calibrate_posicion2(lv_event_t * e);
void calibrate_posicion1(lv_event_t * e);
void calibrate_posicion3(lv_event_t * e);
void calibrate_settings1(lv_event_t * e);
void calibrate_settings2(lv_event_t * e);
void calibrate_settings3(lv_event_t * e);
void calibrate_settings4(lv_event_t * e);
void calibrate_intensidad1(lv_event_t * e);
void calibrate_intensidad2(lv_event_t * e);
void calibrate_intensidad3(lv_event_t * e);
void calibrate_intensidad4(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
