// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Bar4 = NULL;
lv_obj_t * ui_ButtonJoystick3 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_ButtonJoystick1 = NULL;
lv_obj_t * ui_ButtonJoystick2 = NULL;
lv_obj_t * ui_ButtonJoystick4 = NULL;
lv_obj_t * ui_ButtonJoystick5 = NULL;
lv_obj_t * ui_ButtonJoystick6 = NULL;
lv_obj_t * ui_ButtonJoystick7 = NULL;
lv_obj_t * ui_ButtonJoystick8 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Image22 = NULL;
lv_obj_t * ui_Image23 = NULL;
// event funtions
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen9, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen9_screen_init);
    }
}

void ui_event_ButtonJoystick3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrar_brillo(e);
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_ButtonJoystick1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_nrf24(e);
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_ButtonJoystick2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrar_settings(e);
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen7_screen_init);
    }
}

void ui_event_ButtonJoystick4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrar_intensidad(e);
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen8_screen_init);
    }
}

void ui_event_ButtonJoystick5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_joystick(e);
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen6_screen_init);
    }
}

void ui_event_ButtonJoystick6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_boost(e);
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen6_screen_init);
    }
}

void ui_event_ButtonJoystick7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_extra(e);
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen6_screen_init);
    }
}

void ui_event_ButtonJoystick8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrar_direccion(e);
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen6_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -2);
    lv_obj_set_y(ui_Label5, -73);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "CONFIGURACION");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar4 = lv_bar_create(ui_Screen3);
    lv_bar_set_value(ui_Bar4, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar4, 24);
    lv_obj_set_height(ui_Bar4, 10);
    lv_obj_set_x(ui_Bar4, 130);
    lv_obj_set_y(ui_Bar4, -100);
    lv_obj_set_align(ui_Bar4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Bar4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_Bar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Bar4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Bar4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Bar4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0x0DC00C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ButtonJoystick3 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonJoystick3, 65);
    lv_obj_set_height(ui_ButtonJoystick3, 65);
    lv_obj_set_x(ui_ButtonJoystick3, 113);
    lv_obj_set_y(ui_ButtonJoystick3, 69);
    lv_obj_set_align(ui_ButtonJoystick3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick3, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button7, 55);
    lv_obj_set_height(ui_Button7, 55);
    lv_obj_set_x(ui_Button7, -129);
    lv_obj_set_y(ui_Button7, -89);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image2, &ui_img_undo_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image2, -131);
    lv_obj_set_y(ui_Image2, -91);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonJoystick1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonJoystick1, 65);
    lv_obj_set_height(ui_ButtonJoystick1, 65);
    lv_obj_set_x(ui_ButtonJoystick1, 38);
    lv_obj_set_y(ui_ButtonJoystick1, 69);
    lv_obj_set_align(ui_ButtonJoystick1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick1, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonJoystick2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonJoystick2, 65);
    lv_obj_set_height(ui_ButtonJoystick2, 65);
    lv_obj_set_x(ui_ButtonJoystick2, -111);
    lv_obj_set_y(ui_ButtonJoystick2, 68);
    lv_obj_set_align(ui_ButtonJoystick2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick2, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonJoystick4 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonJoystick4, 65);
    lv_obj_set_height(ui_ButtonJoystick4, 65);
    lv_obj_set_x(ui_ButtonJoystick4, -38);
    lv_obj_set_y(ui_ButtonJoystick4, 68);
    lv_obj_set_align(ui_ButtonJoystick4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick4, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonJoystick5 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonJoystick5, 65);
    lv_obj_set_height(ui_ButtonJoystick5, 65);
    lv_obj_set_x(ui_ButtonJoystick5, -111);
    lv_obj_set_y(ui_ButtonJoystick5, -6);
    lv_obj_set_align(ui_ButtonJoystick5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick5, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonJoystick6 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonJoystick6, 65);
    lv_obj_set_height(ui_ButtonJoystick6, 65);
    lv_obj_set_x(ui_ButtonJoystick6, 37);
    lv_obj_set_y(ui_ButtonJoystick6, -4);
    lv_obj_set_align(ui_ButtonJoystick6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick6, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonJoystick7 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonJoystick7, 65);
    lv_obj_set_height(ui_ButtonJoystick7, 65);
    lv_obj_set_x(ui_ButtonJoystick7, 112);
    lv_obj_set_y(ui_ButtonJoystick7, -4);
    lv_obj_set_align(ui_ButtonJoystick7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick7, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonJoystick8 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonJoystick8, 65);
    lv_obj_set_height(ui_ButtonJoystick8, 65);
    lv_obj_set_x(ui_ButtonJoystick8, -37);
    lv_obj_set_y(ui_ButtonJoystick8, -5);
    lv_obj_set_align(ui_ButtonJoystick8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick8, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image6, &ui_img_search_hands_free_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image6, -36);
    lv_obj_set_y(ui_Image6, -4);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image7, &ui_img_pin_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image7, 39);
    lv_obj_set_y(ui_Image7, 69);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image8, &ui_img_brightness_6_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image8, 114);
    lv_obj_set_y(ui_Image8, 70);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image13, &ui_img_speed_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image13, -110);
    lv_obj_set_y(ui_Image13, -5);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image14, &ui_img_local_fire_department_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image14, 37);
    lv_obj_set_y(ui_Image14, -3);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image15, &ui_img_variable_add_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image15, 113);
    lv_obj_set_y(ui_Image15, -3);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image22 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image22, &ui_img_settings_account_box_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image22, -109);
    lv_obj_set_y(ui_Image22, 69);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image23 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image23, &ui_img_android_cell_4_bar_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image23, -37);
    lv_obj_set_y(ui_Image23, 68);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ButtonJoystick3, ui_event_ButtonJoystick3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick1, ui_event_ButtonJoystick1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick2, ui_event_ButtonJoystick2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick4, ui_event_ButtonJoystick4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick5, ui_event_ButtonJoystick5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick6, ui_event_ButtonJoystick6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick7, ui_event_ButtonJoystick7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick8, ui_event_ButtonJoystick8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Label5 = NULL;
    ui_Bar4 = NULL;
    ui_ButtonJoystick3 = NULL;
    ui_Button7 = NULL;
    ui_Image2 = NULL;
    ui_ButtonJoystick1 = NULL;
    ui_ButtonJoystick2 = NULL;
    ui_ButtonJoystick4 = NULL;
    ui_ButtonJoystick5 = NULL;
    ui_ButtonJoystick6 = NULL;
    ui_ButtonJoystick7 = NULL;
    ui_ButtonJoystick8 = NULL;
    ui_Image6 = NULL;
    ui_Image7 = NULL;
    ui_Image8 = NULL;
    ui_Image13 = NULL;
    ui_Image14 = NULL;
    ui_Image15 = NULL;
    ui_Image22 = NULL;
    ui_Image23 = NULL;

}
