// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen8 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Bar8 = NULL;
lv_obj_t * ui_Button11 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_ButtonJoystick16 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_ButtonJoystick17 = NULL;
lv_obj_t * ui_ButtonJoystick18 = NULL;
lv_obj_t * ui_ButtonJoystick19 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Image24 = NULL;
lv_obj_t * ui_Image25 = NULL;
lv_obj_t * ui_Image26 = NULL;
lv_obj_t * ui_Image27 = NULL;
lv_obj_t * ui_Label24 = NULL;
// event funtions
void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_ButtonJoystick16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_intensidad1(e);
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen3_screen_init);
        guardarCambios(e);
        salir_configuracion(e);
    }
}

void ui_event_ButtonJoystick17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_intensidad2(e);
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen3_screen_init);
        guardarCambios(e);
        salir_configuracion(e);
    }
}

void ui_event_ButtonJoystick18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_intensidad3(e);
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen3_screen_init);
        guardarCambios(e);
        salir_configuracion(e);
    }
}

void ui_event_ButtonJoystick19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_intensidad4(e);
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen3_screen_init);
        guardarCambios(e);
        salir_configuracion(e);
    }
}

// build funtions

void ui_Screen8_screen_init(void)
{
    ui_Screen8 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -2);
    lv_obj_set_y(ui_Label18, -73);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "ALCANCE");
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar8 = lv_bar_create(ui_Screen8);
    lv_bar_set_value(ui_Bar8, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar8, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar8, 24);
    lv_obj_set_height(ui_Bar8, 10);
    lv_obj_set_x(ui_Bar8, 130);
    lv_obj_set_y(ui_Bar8, -100);
    lv_obj_set_align(ui_Bar8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Bar8, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_Bar8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Bar8, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Bar8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Bar8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar8, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar8, lv_color_hex(0x0DC00C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar8, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button11 = lv_btn_create(ui_Screen8);
    lv_obj_set_width(ui_Button11, 55);
    lv_obj_set_height(ui_Button11, 55);
    lv_obj_set_x(ui_Button11, -129);
    lv_obj_set_y(ui_Button11, -89);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_img_create(ui_Screen8);
    lv_img_set_src(ui_Image11, &ui_img_undo_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image11, -131);
    lv_obj_set_y(ui_Image11, -91);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonJoystick16 = lv_btn_create(ui_Screen8);
    lv_obj_set_width(ui_ButtonJoystick16, 65);
    lv_obj_set_height(ui_ButtonJoystick16, 65);
    lv_obj_set_x(ui_ButtonJoystick16, -117);
    lv_obj_set_y(ui_ButtonJoystick16, 7);
    lv_obj_set_align(ui_ButtonJoystick16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick16, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick16, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -117);
    lv_obj_set_y(ui_Label19, 68);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Minimo");

    ui_Label20 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 40);
    lv_obj_set_y(ui_Label20, 66);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Normal");

    ui_Label21 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -41);
    lv_obj_set_y(ui_Label21, 67);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Moderado");

    ui_ButtonJoystick17 = lv_btn_create(ui_Screen8);
    lv_obj_set_width(ui_ButtonJoystick17, 65);
    lv_obj_set_height(ui_ButtonJoystick17, 65);
    lv_obj_set_x(ui_ButtonJoystick17, -41);
    lv_obj_set_y(ui_ButtonJoystick17, 7);
    lv_obj_set_align(ui_ButtonJoystick17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick17, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick17, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonJoystick18 = lv_btn_create(ui_Screen8);
    lv_obj_set_width(ui_ButtonJoystick18, 65);
    lv_obj_set_height(ui_ButtonJoystick18, 65);
    lv_obj_set_x(ui_ButtonJoystick18, 35);
    lv_obj_set_y(ui_ButtonJoystick18, 7);
    lv_obj_set_align(ui_ButtonJoystick18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick18, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick18, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonJoystick19 = lv_btn_create(ui_Screen8);
    lv_obj_set_width(ui_ButtonJoystick19, 65);
    lv_obj_set_height(ui_ButtonJoystick19, 65);
    lv_obj_set_x(ui_ButtonJoystick19, 111);
    lv_obj_set_y(ui_ButtonJoystick19, 6);
    lv_obj_set_align(ui_ButtonJoystick19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick19, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick19, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 115);
    lv_obj_set_y(ui_Label22, 65);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Largo\nAlcance");
    lv_obj_set_style_text_align(ui_Label22, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image24 = lv_img_create(ui_Screen8);
    lv_img_set_src(ui_Image24, &ui_img_signal_cellular_0_bar_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image24, -116);
    lv_obj_set_y(ui_Image24, 8);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image25 = lv_img_create(ui_Screen8);
    lv_img_set_src(ui_Image25, &ui_img_signal_cellular_1_bar_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image25, -41);
    lv_obj_set_y(ui_Image25, 8);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image26 = lv_img_create(ui_Screen8);
    lv_img_set_src(ui_Image26, &ui_img_signal_cellular_2_bar_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image26, 35);
    lv_obj_set_y(ui_Image26, 8);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image27 = lv_img_create(ui_Screen8);
    lv_img_set_src(ui_Image27, &ui_img_signal_cellular_4_bar_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image27, 112);
    lv_obj_set_y(ui_Image27, 6);
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 0);
    lv_obj_set_y(ui_Label24, -46);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Alcance actual: Momno");

    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick16, ui_event_ButtonJoystick16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick17, ui_event_ButtonJoystick17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick18, ui_event_ButtonJoystick18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick19, ui_event_ButtonJoystick19, LV_EVENT_ALL, NULL);

}

void ui_Screen8_screen_destroy(void)
{
    if(ui_Screen8) lv_obj_del(ui_Screen8);

    // NULL screen variables
    ui_Screen8 = NULL;
    ui_Label18 = NULL;
    ui_Bar8 = NULL;
    ui_Button11 = NULL;
    ui_Image11 = NULL;
    ui_ButtonJoystick16 = NULL;
    ui_Label19 = NULL;
    ui_Label20 = NULL;
    ui_Label21 = NULL;
    ui_ButtonJoystick17 = NULL;
    ui_ButtonJoystick18 = NULL;
    ui_ButtonJoystick19 = NULL;
    ui_Label22 = NULL;
    ui_Image24 = NULL;
    ui_Image25 = NULL;
    ui_Image26 = NULL;
    ui_Image27 = NULL;
    ui_Label24 = NULL;

}
