// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen7 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Bar7 = NULL;
lv_obj_t * ui_Button10 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_ButtonJoystick13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_ButtonJoystick12 = NULL;
lv_obj_t * ui_ButtonJoystick14 = NULL;
lv_obj_t * ui_ButtonJoystick15 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_Image19 = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_Image21 = NULL;
lv_obj_t * ui_Label23 = NULL;
// event funtions
void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_ButtonJoystick13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_settings1(e);
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen3_screen_init);
        guardarCambios(e);
        salir_configuracion(e);
    }
}

void ui_event_ButtonJoystick12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_settings2(e);
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen3_screen_init);
        guardarCambios(e);
        salir_configuracion(e);
    }
}

void ui_event_ButtonJoystick14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_settings3(e);
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen3_screen_init);
        guardarCambios(e);
        salir_configuracion(e);
    }
}

void ui_event_ButtonJoystick15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_settings4(e);
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen3_screen_init);
        guardarCambios(e);
        salir_configuracion(e);
    }
}

// build funtions

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -2);
    lv_obj_set_y(ui_Label13, -73);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "LOAD SETTINGS");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar7 = lv_bar_create(ui_Screen7);
    lv_bar_set_value(ui_Bar7, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar7, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar7, 24);
    lv_obj_set_height(ui_Bar7, 10);
    lv_obj_set_x(ui_Bar7, 130);
    lv_obj_set_y(ui_Bar7, -100);
    lv_obj_set_align(ui_Bar7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Bar7, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_Bar7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Bar7, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Bar7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Bar7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar7, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar7, lv_color_hex(0x0DC00C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button10 = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_Button10, 55);
    lv_obj_set_height(ui_Button10, 55);
    lv_obj_set_x(ui_Button10, -129);
    lv_obj_set_y(ui_Button10, -89);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_Image10, &ui_img_undo_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image10, -131);
    lv_obj_set_y(ui_Image10, -91);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonJoystick13 = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_ButtonJoystick13, 65);
    lv_obj_set_height(ui_ButtonJoystick13, 65);
    lv_obj_set_x(ui_ButtonJoystick13, -117);
    lv_obj_set_y(ui_ButtonJoystick13, 7);
    lv_obj_set_align(ui_ButtonJoystick13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick13, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -117);
    lv_obj_set_y(ui_Label14, 62);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Preset 1");

    ui_Label15 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 40);
    lv_obj_set_y(ui_Label15, 65);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Preset 3");

    ui_Label16 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -41);
    lv_obj_set_y(ui_Label16, 63);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Preset 2");

    ui_ButtonJoystick12 = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_ButtonJoystick12, 65);
    lv_obj_set_height(ui_ButtonJoystick12, 65);
    lv_obj_set_x(ui_ButtonJoystick12, -41);
    lv_obj_set_y(ui_ButtonJoystick12, 7);
    lv_obj_set_align(ui_ButtonJoystick12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick12, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonJoystick14 = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_ButtonJoystick14, 65);
    lv_obj_set_height(ui_ButtonJoystick14, 65);
    lv_obj_set_x(ui_ButtonJoystick14, 35);
    lv_obj_set_y(ui_ButtonJoystick14, 7);
    lv_obj_set_align(ui_ButtonJoystick14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick14, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick14, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonJoystick15 = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_ButtonJoystick15, 65);
    lv_obj_set_height(ui_ButtonJoystick15, 65);
    lv_obj_set_x(ui_ButtonJoystick15, 111);
    lv_obj_set_y(ui_ButtonJoystick15, 6);
    lv_obj_set_align(ui_ButtonJoystick15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick15, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick15, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 115);
    lv_obj_set_y(ui_Label17, 65);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Preset 4");

    ui_Image18 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_Image18, &ui_img_settings_account_box_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image18, -116);
    lv_obj_set_y(ui_Image18, 7);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image19 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_Image19, &ui_img_settings_account_box_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image19, -40);
    lv_obj_set_y(ui_Image19, 8);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_Image20, &ui_img_settings_account_box_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image20, 36);
    lv_obj_set_y(ui_Image20, 8);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image21 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_Image21, &ui_img_settings_account_box_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image21, 112);
    lv_obj_set_y(ui_Image21, 6);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 7);
    lv_obj_set_y(ui_Label23, -46);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Perfil Actual: 1");

    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick13, ui_event_ButtonJoystick13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick12, ui_event_ButtonJoystick12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick14, ui_event_ButtonJoystick14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick15, ui_event_ButtonJoystick15, LV_EVENT_ALL, NULL);

}

void ui_Screen7_screen_destroy(void)
{
    if(ui_Screen7) lv_obj_del(ui_Screen7);

    // NULL screen variables
    ui_Screen7 = NULL;
    ui_Label13 = NULL;
    ui_Bar7 = NULL;
    ui_Button10 = NULL;
    ui_Image10 = NULL;
    ui_ButtonJoystick13 = NULL;
    ui_Label14 = NULL;
    ui_Label15 = NULL;
    ui_Label16 = NULL;
    ui_ButtonJoystick12 = NULL;
    ui_ButtonJoystick14 = NULL;
    ui_ButtonJoystick15 = NULL;
    ui_Label17 = NULL;
    ui_Image18 = NULL;
    ui_Image19 = NULL;
    ui_Image20 = NULL;
    ui_Image21 = NULL;
    ui_Label23 = NULL;

}
