// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Bar6 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_ButtonJoystick9 = NULL;
lv_obj_t * ui_ButtonJoystick10 = NULL;
lv_obj_t * ui_ButtonJoystick11 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Image17 = NULL;
// event funtions
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_ButtonJoystick9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_posicion2(e);
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_ButtonJoystick10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_posicion1(e);
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_ButtonJoystick11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_posicion3(e);
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -2);
    lv_obj_set_y(ui_Label9, -73);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "CONFIGURACION");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar6 = lv_bar_create(ui_Screen6);
    lv_bar_set_value(ui_Bar6, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar6, 24);
    lv_obj_set_height(ui_Bar6, 10);
    lv_obj_set_x(ui_Bar6, 130);
    lv_obj_set_y(ui_Bar6, -100);
    lv_obj_set_align(ui_Bar6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Bar6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_Bar6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Bar6, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Bar6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Bar6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar6, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar6, lv_color_hex(0x0DC00C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button6, 55);
    lv_obj_set_height(ui_Button6, 55);
    lv_obj_set_x(ui_Button6, -129);
    lv_obj_set_y(ui_Button6, -89);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image9, &ui_img_undo_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image9, -131);
    lv_obj_set_y(ui_Image9, -91);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonJoystick9 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_ButtonJoystick9, 65);
    lv_obj_set_height(ui_ButtonJoystick9, 65);
    lv_obj_set_x(ui_ButtonJoystick9, 0);
    lv_obj_set_y(ui_ButtonJoystick9, -2);
    lv_obj_set_align(ui_ButtonJoystick9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick9, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonJoystick10 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_ButtonJoystick10, 65);
    lv_obj_set_height(ui_ButtonJoystick10, 65);
    lv_obj_set_x(ui_ButtonJoystick10, -95);
    lv_obj_set_y(ui_ButtonJoystick10, -4);
    lv_obj_set_align(ui_ButtonJoystick10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick10, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonJoystick11 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_ButtonJoystick11, 65);
    lv_obj_set_height(ui_ButtonJoystick11, 65);
    lv_obj_set_x(ui_ButtonJoystick11, 94);
    lv_obj_set_y(ui_ButtonJoystick11, -2);
    lv_obj_set_align(ui_ButtonJoystick11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick11, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -95);
    lv_obj_set_y(ui_Label10, 62);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Posicion 1");

    ui_Label11 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 99);
    lv_obj_set_y(ui_Label11, 62);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Posicion 3");

    ui_Label12 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 2);
    lv_obj_set_y(ui_Label12, 62);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Posicion 2");

    ui_Image12 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image12, &ui_img_joystick_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image12, 1);
    lv_obj_set_y(ui_Image12, -1);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image16, &ui_img_joystick_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image16, -94);
    lv_obj_set_y(ui_Image16, -3);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image17, &ui_img_joystick_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image17, 95);
    lv_obj_set_y(ui_Image17, -1);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick9, ui_event_ButtonJoystick9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick10, ui_event_ButtonJoystick10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick11, ui_event_ButtonJoystick11, LV_EVENT_ALL, NULL);

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_Label9 = NULL;
    ui_Bar6 = NULL;
    ui_Button6 = NULL;
    ui_Image9 = NULL;
    ui_ButtonJoystick9 = NULL;
    ui_ButtonJoystick10 = NULL;
    ui_ButtonJoystick11 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Image12 = NULL;
    ui_Image16 = NULL;
    ui_Image17 = NULL;

}
