// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN8_H
#define UI_SCREEN8_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen8
extern void ui_Screen8_screen_init(void);
extern void ui_Screen8_screen_destroy(void);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Bar8;
extern void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Image11;
extern void ui_event_ButtonJoystick16(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick16;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern void ui_event_ButtonJoystick17(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick17;
extern void ui_event_ButtonJoystick18(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick18;
extern void ui_event_ButtonJoystick19(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick19;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_Image26;
extern lv_obj_t * ui_Image27;
extern lv_obj_t * ui_Label24;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

