// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_TextArea1;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern void ui_event_Image5(lv_event_t * e);
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

