// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN7_H
#define UI_SCREEN7_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen7
extern void ui_Screen7_screen_init(void);
extern void ui_Screen7_screen_destroy(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Bar7;
extern void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Image10;
extern void ui_event_ButtonJoystick13(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern void ui_event_ButtonJoystick12(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick12;
extern void ui_event_ButtonJoystick14(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick14;
extern void ui_event_ButtonJoystick15(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick15;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Label23;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

