// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN9_H
#define UI_SCREEN9_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen9
extern void ui_Screen9_screen_init(void);
extern void ui_Screen9_screen_destroy(void);
extern void ui_event_Screen9(lv_event_t * e);
extern lv_obj_t * ui_Screen9;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Bar9;
extern void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Image29;
extern void ui_event_ButtonJoystick24(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick24;
extern lv_obj_t * ui_Image30;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

