// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Bar4;
extern void ui_event_ButtonJoystick3(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick3;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Image2;
extern void ui_event_ButtonJoystick1(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick1;
extern void ui_event_ButtonJoystick2(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick2;
extern void ui_event_ButtonJoystick4(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick4;
extern void ui_event_ButtonJoystick5(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick5;
extern void ui_event_ButtonJoystick6(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick6;
extern void ui_event_ButtonJoystick7(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick7;
extern void ui_event_ButtonJoystick8(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick8;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Image23;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

