// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Bar5 = NULL;
lv_obj_t * ui_BarJoystickIzquierdoSup1 = NULL;
lv_obj_t * ui_BarJoystickIzquierdoSup2 = NULL;
lv_obj_t * ui_BarJoystickIzquierdoSup3 = NULL;
lv_obj_t * ui_BarJoystickIzquierdoSup4 = NULL;
lv_obj_t * ui_BarJoystickIzquierdoSup5 = NULL;
lv_obj_t * ui_BarJoystickIzquierdoSup6 = NULL;
lv_obj_t * ui_BarJoystickIzquierdoSup7 = NULL;
lv_obj_t * ui_BarJoystickIzquierdoSup8 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image28 = NULL;
// event funtions
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -77);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "CONTROLLER");
    lv_obj_clear_flag(ui_Label1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 318);
    lv_obj_set_y(ui_Image3, 3);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bar5 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar5, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar5, 24);
    lv_obj_set_height(ui_Bar5, 10);
    lv_obj_set_x(ui_Bar5, 130);
    lv_obj_set_y(ui_Bar5, -100);
    lv_obj_set_align(ui_Bar5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Bar5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_Bar5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Bar5, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Bar5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Bar5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar5, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar5, lv_color_hex(0x0DC00C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarJoystickIzquierdoSup1 = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_BarJoystickIzquierdoSup1, 0, 255);
    lv_bar_set_value(ui_BarJoystickIzquierdoSup1, 240, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarJoystickIzquierdoSup1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarJoystickIzquierdoSup1, 25);
    lv_obj_set_height(ui_BarJoystickIzquierdoSup1, 83);
    lv_obj_set_x(ui_BarJoystickIzquierdoSup1, -7);
    lv_obj_set_y(ui_BarJoystickIzquierdoSup1, -18);
    lv_obj_set_align(ui_BarJoystickIzquierdoSup1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BarJoystickIzquierdoSup1,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup1, lv_color_hex(0x201C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarJoystickIzquierdoSup1, lv_color_hex(0x34354E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarJoystickIzquierdoSup1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarJoystickIzquierdoSup1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarJoystickIzquierdoSup1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BarJoystickIzquierdoSup1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BarJoystickIzquierdoSup1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BarJoystickIzquierdoSup1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BarJoystickIzquierdoSup1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup1, lv_color_hex(0x956DFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BarJoystickIzquierdoSup1, lv_color_hex(0x088DFF),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BarJoystickIzquierdoSup1, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarJoystickIzquierdoSup2 = lv_bar_create(ui_Screen1);
    lv_bar_set_mode(ui_BarJoystickIzquierdoSup2, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarJoystickIzquierdoSup2, 0, 255);
    lv_bar_set_value(ui_BarJoystickIzquierdoSup2, 255, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarJoystickIzquierdoSup2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarJoystickIzquierdoSup2, 25);
    lv_obj_set_height(ui_BarJoystickIzquierdoSup2, 83);
    lv_obj_set_x(ui_BarJoystickIzquierdoSup2, -7);
    lv_obj_set_y(ui_BarJoystickIzquierdoSup2, 64);
    lv_obj_set_align(ui_BarJoystickIzquierdoSup2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BarJoystickIzquierdoSup2,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup2, lv_color_hex(0x201C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarJoystickIzquierdoSup2, lv_color_hex(0x34354E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarJoystickIzquierdoSup2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BarJoystickIzquierdoSup2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BarJoystickIzquierdoSup2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BarJoystickIzquierdoSup2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BarJoystickIzquierdoSup2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup2, lv_color_hex(0x0088DD), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BarJoystickIzquierdoSup2, lv_color_hex(0x956DFF),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BarJoystickIzquierdoSup2, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarJoystickIzquierdoSup2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarJoystickIzquierdoSup2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarJoystickIzquierdoSup3 = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_BarJoystickIzquierdoSup3, 0, 255);
    lv_bar_set_value(ui_BarJoystickIzquierdoSup3, 240, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarJoystickIzquierdoSup3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarJoystickIzquierdoSup3, 25);
    lv_obj_set_height(ui_BarJoystickIzquierdoSup3, 83);
    lv_obj_set_x(ui_BarJoystickIzquierdoSup3, 40);
    lv_obj_set_y(ui_BarJoystickIzquierdoSup3, -19);
    lv_obj_set_align(ui_BarJoystickIzquierdoSup3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BarJoystickIzquierdoSup3,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup3, lv_color_hex(0x201C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarJoystickIzquierdoSup3, lv_color_hex(0x34354E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarJoystickIzquierdoSup3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarJoystickIzquierdoSup3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarJoystickIzquierdoSup3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BarJoystickIzquierdoSup3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BarJoystickIzquierdoSup3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BarJoystickIzquierdoSup3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BarJoystickIzquierdoSup3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup3, lv_color_hex(0x956DFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BarJoystickIzquierdoSup3, lv_color_hex(0x088DFF),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BarJoystickIzquierdoSup3, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarJoystickIzquierdoSup4 = lv_bar_create(ui_Screen1);
    lv_bar_set_mode(ui_BarJoystickIzquierdoSup4, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarJoystickIzquierdoSup4, 0, 255);
    lv_bar_set_value(ui_BarJoystickIzquierdoSup4, 255, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarJoystickIzquierdoSup4, 155, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarJoystickIzquierdoSup4, 25);
    lv_obj_set_height(ui_BarJoystickIzquierdoSup4, 83);
    lv_obj_set_x(ui_BarJoystickIzquierdoSup4, 40);
    lv_obj_set_y(ui_BarJoystickIzquierdoSup4, 63);
    lv_obj_set_align(ui_BarJoystickIzquierdoSup4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BarJoystickIzquierdoSup4,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup4, lv_color_hex(0x201C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarJoystickIzquierdoSup4, lv_color_hex(0x34354E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarJoystickIzquierdoSup4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BarJoystickIzquierdoSup4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BarJoystickIzquierdoSup4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BarJoystickIzquierdoSup4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BarJoystickIzquierdoSup4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup4, lv_color_hex(0x0088DD), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BarJoystickIzquierdoSup4, lv_color_hex(0x956DFF),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BarJoystickIzquierdoSup4, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarJoystickIzquierdoSup4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarJoystickIzquierdoSup4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarJoystickIzquierdoSup5 = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_BarJoystickIzquierdoSup5, 0, 255);
    lv_bar_set_value(ui_BarJoystickIzquierdoSup5, 240, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarJoystickIzquierdoSup5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarJoystickIzquierdoSup5, 25);
    lv_obj_set_height(ui_BarJoystickIzquierdoSup5, 83);
    lv_obj_set_x(ui_BarJoystickIzquierdoSup5, 86);
    lv_obj_set_y(ui_BarJoystickIzquierdoSup5, -18);
    lv_obj_set_align(ui_BarJoystickIzquierdoSup5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BarJoystickIzquierdoSup5,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup5, lv_color_hex(0x201C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarJoystickIzquierdoSup5, lv_color_hex(0x34354E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarJoystickIzquierdoSup5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarJoystickIzquierdoSup5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarJoystickIzquierdoSup5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BarJoystickIzquierdoSup5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BarJoystickIzquierdoSup5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BarJoystickIzquierdoSup5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BarJoystickIzquierdoSup5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup5, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup5, lv_color_hex(0x956DFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BarJoystickIzquierdoSup5, lv_color_hex(0x088DFF),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BarJoystickIzquierdoSup5, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarJoystickIzquierdoSup6 = lv_bar_create(ui_Screen1);
    lv_bar_set_mode(ui_BarJoystickIzquierdoSup6, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarJoystickIzquierdoSup6, 0, 255);
    lv_bar_set_value(ui_BarJoystickIzquierdoSup6, 255, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarJoystickIzquierdoSup6, 155, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarJoystickIzquierdoSup6, 25);
    lv_obj_set_height(ui_BarJoystickIzquierdoSup6, 83);
    lv_obj_set_x(ui_BarJoystickIzquierdoSup6, 86);
    lv_obj_set_y(ui_BarJoystickIzquierdoSup6, 65);
    lv_obj_set_align(ui_BarJoystickIzquierdoSup6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BarJoystickIzquierdoSup6,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup6, lv_color_hex(0x201C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarJoystickIzquierdoSup6, lv_color_hex(0x34354E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarJoystickIzquierdoSup6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BarJoystickIzquierdoSup6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BarJoystickIzquierdoSup6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BarJoystickIzquierdoSup6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BarJoystickIzquierdoSup6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup6, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup6, lv_color_hex(0x0088DD), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BarJoystickIzquierdoSup6, lv_color_hex(0x956DFF),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BarJoystickIzquierdoSup6, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarJoystickIzquierdoSup6, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarJoystickIzquierdoSup6, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarJoystickIzquierdoSup7 = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_BarJoystickIzquierdoSup7, 0, 255);
    lv_bar_set_value(ui_BarJoystickIzquierdoSup7, 240, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarJoystickIzquierdoSup7, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarJoystickIzquierdoSup7, 25);
    lv_obj_set_height(ui_BarJoystickIzquierdoSup7, 83);
    lv_obj_set_x(ui_BarJoystickIzquierdoSup7, 130);
    lv_obj_set_y(ui_BarJoystickIzquierdoSup7, -18);
    lv_obj_set_align(ui_BarJoystickIzquierdoSup7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BarJoystickIzquierdoSup7,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup7, lv_color_hex(0x201C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarJoystickIzquierdoSup7, lv_color_hex(0x34354E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarJoystickIzquierdoSup7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarJoystickIzquierdoSup7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarJoystickIzquierdoSup7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BarJoystickIzquierdoSup7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BarJoystickIzquierdoSup7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BarJoystickIzquierdoSup7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BarJoystickIzquierdoSup7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup7, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup7, lv_color_hex(0x956DFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BarJoystickIzquierdoSup7, lv_color_hex(0x088DFF),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BarJoystickIzquierdoSup7, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarJoystickIzquierdoSup8 = lv_bar_create(ui_Screen1);
    lv_bar_set_mode(ui_BarJoystickIzquierdoSup8, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_BarJoystickIzquierdoSup8, 0, 255);
    lv_bar_set_value(ui_BarJoystickIzquierdoSup8, 255, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarJoystickIzquierdoSup8, 155, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarJoystickIzquierdoSup8, 25);
    lv_obj_set_height(ui_BarJoystickIzquierdoSup8, 83);
    lv_obj_set_x(ui_BarJoystickIzquierdoSup8, 130);
    lv_obj_set_y(ui_BarJoystickIzquierdoSup8, 65);
    lv_obj_set_align(ui_BarJoystickIzquierdoSup8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BarJoystickIzquierdoSup8,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup8, lv_color_hex(0x201C29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BarJoystickIzquierdoSup8, lv_color_hex(0x34354E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BarJoystickIzquierdoSup8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BarJoystickIzquierdoSup8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BarJoystickIzquierdoSup8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BarJoystickIzquierdoSup8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BarJoystickIzquierdoSup8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BarJoystickIzquierdoSup8, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BarJoystickIzquierdoSup8, lv_color_hex(0x0088DD), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarJoystickIzquierdoSup8, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BarJoystickIzquierdoSup8, lv_color_hex(0x956DFF),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BarJoystickIzquierdoSup8, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BarJoystickIzquierdoSup8, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BarJoystickIzquierdoSup8, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button5, 55);
    lv_obj_set_height(ui_Button5, 55);
    lv_obj_set_x(ui_Button5, -129);
    lv_obj_set_y(ui_Button5, -88);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_settings_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image1, -130);
    lv_obj_set_y(ui_Image1, -90);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image28 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image28, &ui_img_speed_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image28, -90);
    lv_obj_set_y(ui_Image28, 11);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Label1 = NULL;
    ui_Image3 = NULL;
    ui_Bar5 = NULL;
    ui_BarJoystickIzquierdoSup1 = NULL;
    ui_BarJoystickIzquierdoSup2 = NULL;
    ui_BarJoystickIzquierdoSup3 = NULL;
    ui_BarJoystickIzquierdoSup4 = NULL;
    ui_BarJoystickIzquierdoSup5 = NULL;
    ui_BarJoystickIzquierdoSup6 = NULL;
    ui_BarJoystickIzquierdoSup7 = NULL;
    ui_BarJoystickIzquierdoSup8 = NULL;
    ui_Button5 = NULL;
    ui_Image1 = NULL;
    ui_Image28 = NULL;

}
