// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Bar6;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Image9;
extern void ui_event_ButtonJoystick9(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick9;
extern void ui_event_ButtonJoystick10(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick10;
extern void ui_event_ButtonJoystick11(lv_event_t * e);
extern lv_obj_t * ui_ButtonJoystick11;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Image17;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

