// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen9 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Bar9 = NULL;
lv_obj_t * ui_Button12 = NULL;
lv_obj_t * ui_Image29 = NULL;
lv_obj_t * ui_ButtonJoystick24 = NULL;
lv_obj_t * ui_Image30 = NULL;
// event funtions
void ui_event_Screen9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_ButtonJoystick24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        calibrate_canal(e);
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen9_screen_init(void)
{
    ui_Screen9 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_Screen9);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -2);
    lv_obj_set_y(ui_Label25, -73);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "CONFIGURACION");
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar9 = lv_bar_create(ui_Screen9);
    lv_bar_set_value(ui_Bar9, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar9, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar9, 24);
    lv_obj_set_height(ui_Bar9, 10);
    lv_obj_set_x(ui_Bar9, 130);
    lv_obj_set_y(ui_Bar9, -100);
    lv_obj_set_align(ui_Bar9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Bar9, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_Bar9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Bar9, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Bar9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Bar9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar9, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar9, lv_color_hex(0x0DC00C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar9, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button12 = lv_btn_create(ui_Screen9);
    lv_obj_set_width(ui_Button12, 55);
    lv_obj_set_height(ui_Button12, 55);
    lv_obj_set_x(ui_Button12, -129);
    lv_obj_set_y(ui_Button12, -89);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image29 = lv_img_create(ui_Screen9);
    lv_img_set_src(ui_Image29, &ui_img_undo_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image29, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image29, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image29, -131);
    lv_obj_set_y(ui_Image29, -91);
    lv_obj_set_align(ui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonJoystick24 = lv_btn_create(ui_Screen9);
    lv_obj_set_width(ui_ButtonJoystick24, 65);
    lv_obj_set_height(ui_ButtonJoystick24, 65);
    lv_obj_set_x(ui_ButtonJoystick24, -111);
    lv_obj_set_y(ui_ButtonJoystick24, -6);
    lv_obj_set_align(ui_ButtonJoystick24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonJoystick24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonJoystick24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonJoystick24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonJoystick24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonJoystick24, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonJoystick24, lv_color_hex(0x585757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonJoystick24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image30 = lv_img_create(ui_Screen9);
    lv_img_set_src(ui_Image30, &ui_img_cell_tower_50dp_15b9a8_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image30, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image30, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image30, -110);
    lv_obj_set_y(ui_Image30, -6);
    lv_obj_set_align(ui_Image30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonJoystick24, ui_event_ButtonJoystick24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen9, ui_event_Screen9, LV_EVENT_ALL, NULL);

}

void ui_Screen9_screen_destroy(void)
{
    if(ui_Screen9) lv_obj_del(ui_Screen9);

    // NULL screen variables
    ui_Screen9 = NULL;
    ui_Label25 = NULL;
    ui_Bar9 = NULL;
    ui_Button12 = NULL;
    ui_Image29 = NULL;
    ui_ButtonJoystick24 = NULL;
    ui_Image30 = NULL;

}
